/**
 * A dummy object containing all possible properties for
 * @type {{number_of_participant: string, supply_with_vat: string, oj_digital: string, is_economic_capacity: string, complaint_files: {file: {name: string, checked: string}}, has_quality_criterion: string, field_h_81: string, scopes_of_activity: string, contract_days: string, mean_to_short: string, consideration_date_stamp: string, zip_code: string, has_middleman_question2: string, has_middleman_question1: string, eu_fund_info: string, innovativeSolution_req: string, max_businessman_num: string, item_list: {item: {cpv_list: {cpv: string}, main_cpv: {code: string, en: string, lv: string, code_num: string, type: string}, description: string, service_types: string, contract_name: string, state_procurement: string, additional_cpv_list: string}}, consideration_minute: string, set_global_data_version: string, submission_date_stamp: string, field_c_81: string, interrupt_date: string, cancel_user: string, price_from: string, procurement_is_terminated: string, administrative_info: {submit_hour: string, urgent_text: string, tender_open_minute: string, oj_digital: string, allowed_persons: string, allowed: string, language: string, document_request_minute: string, document_request_hour: string, send_date: string, digital_access: string, payment: string, urgent: string, submit_date: string, submit_date_stamp: string, oj_list: string, previous_publications_other: string, previous_publications_oj: string, document_request_date: string, publication_list: string, previous_publications: string, tender_open_date: string, tender_open_hour: string, submit_minute: string, tender_open_place: string}, added_date_stamp: string, previous_publications_oj: string, other_type: string, creation_date: string, other_notes: string, court: string, doc_places: string, ted_published_url: string, extra_winners_reason: string, has_middleman_question_central_purchasing: string, authority_name: string, supply_price_exact: string, end_date: string, environment_req: string, field_b_81: string, old_authority_id: string, renewal_enabled: string, candidate_criteria_list: {criteria: {name: string}}, attachments: {file: {name: string, content: string}}, complaint_file: string, statistics_version: string, overall_contract_checked: string, field_note: string, checking_started: string, part_2: {price_exact: string, price_exact_eur: string}, linked_notice_id: string, contract_end_date: string, archived: string, submission_date: string, publish_price: string, one_businessman: string, renewal_times_from: string, docs_place: string, notice_sent_date: string, contract_currency: string, first_approval_date_stamp: string, currency: string, submit_date: string, vat_rate: string, winners: {winner: {firm: string, country: string, reg_num: string, address: string, price: string}}, businessman_num: string, has_reserved_right_contract: string, address: string, docs_minute_from: string, decision: string, renewal: string, interruption_date_stamp: string, invitation_publication_date: string, procedure: {candidates_selected: string, candidates: {country: string, address: string, city: string, reg_nr: string, name: string}, argument: string, tenderer_count_min: string, criteria: string, count_restrictions: string, tenderer_count_max: string, proc_type: string, tenderer_decrease: string, tenderer_count_expected: string}, documentation_online: string, publication_list: {publication: {pub_date: string, pub_type: string}}, additional_cpv_list: string, field_m_81: string, applicant: string, publication_date_stamp: string, timelimits: {dok_req_date: string, submit_hour: string, tender_open_minute: string, tender_open_hour: string, submit_minute: string, work_time: string, tender_open_place: string, submit_date: string, submit_date_stamp: string, tender_open_date: string}, authority_reg_num: string, renewal_details: string, innovativeSolution_req_detail: string, days: string, contract_months: string, code_num: string, is_profession_reserved: string, tenderer_count_expected: string, supply_vat_rate: string, submit_hour: string, country: string, use_complaint_file: string, is_technical_capacity: string, update_date_stamp: string, field_d_81: string, notes: string, language: string, checker_id: string, document_id: string, basic_contract_years: string, notice_cpv_type: string, contract_start_date: string, shifted_days_settings: {}, complaint_id: string, notice_send_date: string, middleman: string, eur_conv_version: string, applicant_email: string, submit_place: string, price_indications: {indication: string}, supplement_3_4: {prof_qualification: string, prof_qual_text: string}, auction_description: string, source_notice: string, docs_hour_from: string, info: string, procedure_regulations_url: string, offers: {firm: Array, country: Array, reg_num: Array, address: Array}, oj_list: {}, has_complaint: string, approval_date: string, eu_authority: string, procedure_notes: string, invitation: string, renewal_times_to: string, en: string, socialResponsibility_req: string, update_date: string, previous_publications: string, field_o_81: string, consideration_date: string, parts: string, max_count_parts_client_count: string, economic_capacity_document: string, region: string, supply_currency: string, contract_publication_oj_num: string, changes_type: string, field_m: string, field_description: string, supply_types: string, changes: string, field_g: string, description: string, supply_price_min: string, field_h: string, field_e: string, field_f: string, field_k: string, field_l: string, parts_list: {part: {nr: Array, name: Array, checked: Array, part_ip_list: Array, enabled: Array, part_has_complaint: Array}}, indefinite: string, field_i: string, content: string, field_j: string, auction: string, docs_date_from: string, supplement_2: {currency: string, basic_contract: string, region: string, state_procurement: string}, field_n_81: string, supplement_3: {other_conditions: string, reserved: string, guarantee: string, groups: string, financial_rules: string, technical_requirements: string, financial_requirements_min: string, financial_requirements: string, technical_requirements_min: string, other_conditions_details: string, businessman_requirements: string}, building_types: string, offers2: string, scope: string, tenderer_count_max: string, extra_winners: string, submit_date_stamp: string, no_doc_ext: string, docs_date_to: string, cpv_list: {cpv: {en: string, lv: string}}, decision_2: string, added_date: string, contract_expects: string, has_count_parts_client: string, socialResponsibility_req_detail: string, contract_price_from: string, field_i_81: string, proc_type: string, price_to: string, contract_name: string, cpv_b: string, cpv_a: string, consideration_hour: string, dynamic_purchasing: string, contract_publication_oj_date: string, basic_contract_price_to: string, field_c: string, field_d: string, submit_places: string, notice_send_date_stamp: string, field_a: string, field_b: string, criteria_list: {}, contract_amount: string, no_doc_ext_f14: string, subcontract_amount_max: string, criteria: string, tender_for_parts: string, complaint_subject: string, overall_contract_data: string, variants: string, type: string, info_places: string, eu_fund: string, price: string, options: string, payment: string, economic_capacity: string, id: string, contract_publication_date: string, fax: {}, interrupt_user_id: string, renewal_times: string, basic_contract_frequency: string, supplement_2b: {end_date: string, notes: string, price_from: string, months: string, price_exact: string, price_to: string, description: string, basic_contract: string, state_procurement: string, procedure_start_date: string, service_types: string, days: string, currency: string, place: string, region: string, start_date: string}, source_notice_has_url3: string, techical_capacity_document: string, eu_list: string, captcha_test: string, interrupt_info: string, price_exact: string, customer_reg_num: string, mail_text: string, field_k_81: string, field: string, additional_info: {approval_date_stamp: string, update_date_stamp: string, approval_date: string, update_date: string}, phone: string, options_description: string, populate_iub_winners: string, service_types: string, global_winner_title: string, contract_price_exact: string, status: string, is_dinamic_purchasing: string, invitation_id: string, basic_contract_currency: string, changes_info: {additional_work: string, price_before: string, unexpected_changes_description: string, price_after: string, changes_description: string, unexpected_changes: string, currency_before: string, currency_after: string}, options_months: string, city: string, docs_minute_to: string, export_version: string, range: string, has_url3: string, authority_id: string, field_j_81: string, has_url4: string, notice_point: string, overall_contract: string, publication_date: string, place: string, supply_price_exact_lvl: string, eis_id: string, subcontract_info: string, techical_professional_capacity: string, start_date: string, basic_contract_months: string, field_e_81: string, contract_performance_conditions: string, docs_hour_to: string, suspension_reason: string, field_e1: string, search_version: string, field_e2: string, environment_req_detail: string, submit_minute: string, contract_approval_date: string, previous_open_date: string, reserved_right_contract: string, other_language: string, global_winner_reg_num: string, date: string, argument: {}, part_5_list: {part_5: {contract_price_exact_lvl: string, without_results: string, publicate_winner: string, product_country: string, contract_with_vat: string, initial_currency: string, decision_date: string, years_expenses: string, exact_currency_secret: string, subcontract_price: string, concluded_contract_name: string, contract_currency: string, low_offers: string, winner_with_variants: string, lower_currency: string, product_from_eu: string, criteria_type: string, party_nr: string, tender_num: string, party_nr_secret: string, contract_price_exact_secret: string, contract_vat_rate: string, interrupt_info: string, contract_price_from: string, contract_price_to: string, subcontract_proportion: string, initial_price: string, subcontract_unknown: string, interrupted: string, part_nr: string, subcontract_currency: string, exact_currency: string, months_expenses: string, contract_price_exact_secret_lvl: string, lower_price: string, contract_count: string, contract_price_exact: string, subcontracts: string, value_description: string, winner_list: {winner: {winner_reg_num: string, winner_phone: string, winner_city: string, winner_name: string, publication_date: string, winner_zip_code: string, price_exact_eur: string, winner_country: string, winner_fax: string, winner_address: string, winner_email: string, winner_url: string}}, contract_nr: string}}, subject: string, tender_full_url: string, publisher_phone: string, lv: string, has_middleman_question_total_procurement: string, field_l_81: string, interlocutory_files: {file: {name: string, checked: string}}, iub_publication_date: string, new_scopes: {}, send_date: string, tender_mvu_num: string, divided_in_parts: string, funds: string, price_exact_lvl: string, criteria_type: string, months: string, main_cpv: {number_of_participant: string, approval_date: string, code: string, en: string, lv: string, cpv_b: string, contract_price_exact: string, code_num: string, type: string, cpv_a: string, authority_name: string}, interrupted: string, state_procurement: string, basic_contract_price_from: string, field_g_81: string, participation_date: string, max_count_parts: string, invitation_number: string, parent_id: string, person: string, customer_email: string, publicate: string, contactplaces: {contactplace: {country: string, reg_num: string, address: string, city: string, tender_submit_url: string, type: string, zip_code: string, url: string, phone: string, person: string, url_client: string, name: string, short_name: string, place: string, fax: string, email: string, procurement_doc_url: string}}, procurement_code: string, with_vat: string, code: string, tenderer_count_min: string, has_url: string, financial_info: string, is_suspended: string, included_total_procurement: string, abroad_competitor_num: string, field_f_81: string, decision_date: string, general: {procurement_type: string, country: string, has_publication_in_accordance: string, price_from: string, address: string, cpv_list: {cpv: {code: string, en: string, lv: string}}, city: string, procurement_year: string, main_cpv: {number_of_participant: string, approval_date: string, code: string, en: string, lv: string, cpv_b: string, contract_price_exact: string, code_num: string, type: string, cpv_a: string, authority_name: string}, price_to: string, authority_id: string, zip_code: string, additional_cpv_list: string, dummy: string, authority_reg_num: string, procurement_id: string, name: string, previous_open_date: string, authority_name: string, procurement_code: string}, environment_green_group: string, document_is_empty: string, contract_date: string, delivery_timetable_months: string, design: string, middleman_list: {middleman_item: {country: string, reg_num: string, address: string, auth_id: string, city: string, name: string, zip_code: string}}, supply_price_max: string, offer_valid_before: string, competitor_num: string, middleman_search_name: {}, reg_num: string, basic_contract_sum_value: string, field_a_81: string, previous_publications_other: string, contract_price_to: string, is_staff_qualification: string, suitability_professional_activity: string, delivery_timetable_days: string, approval_date_stamp: string, subcontract_amount_min: string, authority_types: string, cost_criteria_type: string, send_oj: string, service_type: {}, has_basic_contract: string, field_soc_b: string, field_soc_a: string, field_soc_d: string, field_soc_c: string, field_soc_f: string, has_suspension_of_procedures: string, field_soc_e: string, price_exact_eur: string, basic_contract_argument: string, field_soc_g: string, creation_date_stamp: string, winner_list: {winner: {winner_reg_num: string, winner_phone: string, winner_city: string, winner_name: string, publication_date: string, winner_zip_code: string, price_exact_eur: string, winner_country: string, winner_fax: string, winner_address: string, winner_email: string, winner_url: string}}, interested_persons: {person: {use_email: string, participated: string, name: string, fax: string, email: string}[]}, options_days: string, first_approval_date: string, new_info: {main_cpv: {code: string, en: string, lv: string, code_num: string, type: string}, description: string, contract_days: string, contract_start_date: string, contract_end_date: string, group_assigned_contract: string, exact_currency: string, price_exact_lvl: string, place: string, contract_months: string, basic_contract_argument: string, contract_price_exact: string, region: string, winner_list: {winner: {winner_reg_num: string, winner_phone: string, winner_city: string, winner_nuts: string, winner_name: string, winner_zip_code: string, winner_country: string, winner_mvu: string, winner_fax: string, winner_address: string, winner_email: string, winner_url: string}}}, customer: string}}
 */
export const properties = {
  document_id: '',
  id: '',
  source_notice: '',
  status: '',
  general: {
    procurement_code: '',
    procurement_id: '',
    dummy: '', // boolean
    main_cpv: {
      code: '',
      code_num: '',
      type: '',
      lv: '',
      en: '',
      cpv_a: '',
      cpv_b: '',
      authority_name: '',
      contract_price_exact: '',
      number_of_participant: '',
      approval_date: '',
    },
    name: '',
    price_from: '',
    price_to: '',
    procurement_type: '',
    authority_id: '',
    authority_name: '',
    authority_reg_num: '',
    address: '',
    city: '',
    zip_code: '',
    country: '',
    procurement_year: '',
    cpv_list: {
      cpv: {
        code: '',
        lv: '',
        en: '',
      }
    },
    additional_cpv_list: '',
    previous_open_date: '',
    has_publication_in_accordance: '',
  },
  main_cpv: {
    code: '',
    code_num: '',
    type: '',
    lv: '',
    en: '',
    cpv_a: '',
    cpv_b: '',
    authority_name: '',
    contract_price_exact: '',
    number_of_participant: '',
    approval_date: '',
  },
  divided_in_parts: '',
  contract_name: '',
  place: '',
  region: '',
  eu_fund: '',
  environment_req: '',
  approval_date_stamp: '',
  parts: '',
  part_5_list: {
    part_5: {
      contract_nr: '',
      part_nr: '',
      concluded_contract_name: '',
      decision_date: '',
      tender_num: '',
      initial_price: '',
      initial_currency: '',
      contract_price_exact: '',
      exact_currency: '',
      contract_price_from: '',
      contract_price_to: '',
      contract_with_vat: '',
      contract_vat_rate: '',
      contract_currency: '',
      subcontracts: '',
      subcontract_price: '',
      subcontract_currency: '',
      subcontract_proportion: '',
      subcontract_unknown: '',
      value_description: '',
      without_results: '',
      interrupted: '',
      interrupt_info: '',
      lower_price: '',
      lower_currency: '',
      contract_count: '',
      product_from_eu: '',
      product_country: '',
      criteria_type: '',
      winner_with_variants: '',
      low_offers: '',
      years_expenses: '',
      months_expenses: '',
      contract_price_exact_lvl: '',
      contract_price_exact_secret_lvl: '',
      contract_price_exact_secret: '',
      exact_currency_secret: '',
      publicate_winner: '',
      party_nr: '',
      party_nr_secret: '',
      winner_list: {
        winner: {
          winner_name: '',
          winner_reg_num: '',
          winner_address: '',
          winner_city: '',
          winner_zip_code: '',
          winner_country: '',
          winner_phone: '',
          winner_fax: '',
          winner_email: '',
          winner_url: '',
          publication_date: '',
          price_exact_eur: '',
        }
      },
    }
  },
  authority_name: '',
  address: '',
  authority_reg_num: '',
  zip_code: '',
  city: '',
  country: '',
  middleman: '',
  creation_date: '',
  creation_date_stamp: '',
  authority_id: '',
  contactplaces: {
    contactplace: {
      type: '',
      name: '',
      short_name: '',
      reg_num: '',
      address: '',
      city: '',
      zip_code: '',
      country: '',
      place: '',
      person: '',
      phone: '',
      fax: '',
      email: '',
      url: '',
      url_client: '',
      procurement_doc_url: '',
      tender_submit_url: '',
    }
  },
  description: '',
  price_exact: '',
  currency: '',
  eu_list: '',
  type: '',
  approval_date: '',
  publication_date: '',
  publication_date_stamp: '',
  statistics_version: '',
  price_exact_eur: '',
  eur_conv_version: '',
  global_winner_title: '',
  global_winner_reg_num: '',
  set_global_data_version: '',
  populate_iub_winners: '',
  archived: '',
  additional_info: {
    approval_date: '',
    approval_date_stamp: '',
    update_date: '',
    update_date_stamp: '',
  },
  part_2: {
    price_exact: '',
    price_exact_eur: '',
  },
  winner_list: {
    winner: {
      winner_name: '',
      winner_reg_num: '',
      winner_address: '',
      winner_city: '',
      winner_zip_code: '',
      winner_country: '',
      winner_phone: '',
      winner_fax: '',
      winner_email: '',
      winner_url: '',
      publication_date: '',
      price_exact_eur: '',
    }
  },
  code: '',
  code_num: '',
  lv: '',
  en: '',
  cpv_a: '',
  cpv_b: '',
  contract_price_exact: '',
  number_of_participant: '',


  supply_price_exact_lvl: '',
  supply_vat_rate: '',
  supply_price_max: '',
  supply_price_min: '',
  supply_price_exact: '',
  supply_with_vat: '',
  supply_currency: '',
  mean_to_short: '',
  mail_text: '',
  use_complaint_file: '',
  customer_email: '',
  applicant_email: '',
  complaint_file: '',
  interlocutory_files: {
    file: {
      checked: '', // boolean
      name: '',
    }
  },
  complaint_files: {
    file: {
      checked: '', // boolean
      name: '',
    }
  },
  parts_list: {
    part: {
      enabled: [],
      checked: [],
      name: [],
      nr: [],
      part_has_complaint: [],
      part_ip_list: [],
    }
  },
  interested_persons: {
    person: [
      {
        name: '',
        email: '',
        use_email: '',
        fax: '',
        participated: '',
      }
    ]
  },
  added_date: '',
  added_date_stamp: '',
  consideration_date_stamp: '',
  submission_date_stamp: '',
  court: '',
  decision_2: '',
  decision: '',
  consideration_minute: '',
  consideration_hour: '',
  consideration_date: '',
  complaint_subject: '',
  funds: '',
  field: '',
  scope: '',
  customer_reg_num: '',
  customer: '',
  applicant: '',
  submission_date: '',
  invitation_number: '',
  eu_fund_info: '',
  authority_types: '',
  procurement_code: '',
  item_list: {
    item: {
      contract_name: '',
      description: '',
      state_procurement: '', // boolean
      service_types: '',
      main_cpv: {
        code: '',
        code_num: '',
        type: '',
        lv: '',
        en: '',
      },
      cpv_list: {
        cpv: '',
      },
      additional_cpv_list: '', // boolean
    }
  },
  criteria: '',
  tenderer_count_max: '',
  tenderer_count_min: '',
  tenderer_count_expected: '',
  previous_open_date: '',
  payment: '',
  scopes_of_activity: '',
  other_type: '',
  notice_point: '',
  old_authority_id: '',
  notice_sent_date: '',
  iub_publication_date: '',
  captcha_test: '',
  publisher_phone: '',
  changes: '',
  no_doc_ext_f14: '',
  price_indications: {
    indication: '',
  },
  docs_minute_to: '',
  docs_hour_to: '',
  docs_minute_from: '',
  docs_hour_from: '',
  docs_date_to: '',
  docs_date_from: '',
  docs_place: '',
  offer_valid_before: '',
  invitation_id: '',
  send_date: '',
  reg_num: '',
  contract_publication_oj_date: '',
  contract_publication_oj_num: '',
  contract_publication_date: '',
  contract_approval_date: '',
  eis_id: '',
  source_notice_has_url3: '', // boolean
  ted_published_url: '',
  design: '',
  linked_notice_id: '',
  subcontract_amount_max: '',
  subcontract_amount_min: '',
  subcontract_info: '',
  other_language: '',
  renewal_details: '',
  renewal: '',
  indefinite: '',
  has_quality_criterion: '',
  cost_criteria_type: '',
  additional_cpv_list: '',
  cpv_list: { // can this be an array?
    cpv: {
      lv: '',
      en: '',
    }
  },
  invitation: '',
  document_is_empty: '',
  search_version: '',
  participation_date: '',
  has_url: '', // boolean
  publish_price: '', // boolean
  changes_info: {
    changes_description: '',
    additional_work: '',
    unexpected_changes: '',
    unexpected_changes_description: '',
    price_before: '',
    currency_before: '',
    price_after: '',
    currency_after: '',
  },
  new_info: {
    place: '',
    region: '',
    description: '',
    contract_months: '',
    contract_days: '',
    contract_start_date: '',
    contract_end_date: '',
    basic_contract_argument: '',
    group_assigned_contract: '',
    contract_price_exact: '',
    exact_currency: '',
    price_exact_lvl: '',
    winner_list: {
      winner: {
        winner_name: '',
        winner_reg_num: '',
        winner_address: '',
        winner_city: '',
        winner_zip_code: '',
        winner_nuts: '',
        winner_country: '',
        winner_phone: '',
        winner_fax: '',
        winner_email: '',
        winner_url: '',
        winner_mvu: '',
      }
    },
    main_cpv: {
      code: '',
      code_num: '',
      type: '',
      lv: '',
      en: '',
    }
  },
  export_version: '',
  tender_mvu_num: '',
  shifted_days_settings: {}, // this has properties as dates e.g.  { 'setting_2017-05-05': { _text: '2017-05-13 ' }
  renewal_enabled: '',
  parent_id: '', // what is this????
  is_staff_qualification: '',
  contract_performance_conditions: '',
  is_profession_reserved: '',
  techical_capacity_document: '', // typo????
  techical_professional_capacity: '',
  is_technical_capacity: '',
  economic_capacity_document: '',
  economic_capacity: '',
  is_economic_capacity: '',
  suitability_professional_activity: '',
  financial_info: '',
  suspension_reason: '',
  has_suspension_of_procedures: '',
  is_suspended: '', // boolean
  is_dinamic_purchasing: '', // typo????
  overall_contract_data: '',
  overall_contract_checked: '',
  overall_contract: '',
  has_middleman_question2: '',
  has_middleman_question1: '',
  procedure_notes: '',
  procedure_regulations_url: '',
  dynamic_purchasing: '',
  procurement_is_terminated: '',
  has_count_parts_client: '',
  max_count_parts: '',
  max_count_parts_client_count: '',
  changes_type: '',
  innovativeSolution_req_detail: '',
  socialResponsibility_req_detail: '',
  range: '',
  has_basic_contract: '',
  candidate_criteria_list: {
    criteria: {
      name: '',
    }
  },
  has_reserved_right_contract: '',
  reserved_right_contract: '',
  has_middleman_question_total_procurement: '',
  has_middleman_question_central_purchasing: '',
  socialResponsibility_req: '',
  innovativeSolution_req: '',
  environment_green_group: '',
  has_url3: '',
  has_url4: '',
  tender_full_url: '',
  included_total_procurement: '',
  one_businessman: '',
  interrupt_date: '',
  interrupted: '', // boolean
  interrupt_user_id: '',
  interruption_date_stamp: '',
  competitor_num: '',
  abroad_competitor_num: '',
  basic_contract_months: '',
  basic_contract_currency: '',
  businessman_num: '',
  max_businessman_num: '',
  basic_contract_years: '',
  basic_contract_argument: '',
  basic_contract_price_from: '',
  basic_contract_price_to: '',
  basic_contract_frequency: '',
  interrupt_info: '',
  invitation_publication_date: '',
  decision_date: '',
  contract_date: '',
  winners: { // can this be an array?
    winner: {
      firm: '',
      reg_num: '',
      address: '',
      country: '',
      price: '',
    },
  },
  offers: { // can this be an array?
    firm: [], // what is the type????
    reg_num: [], // what is the type????
    country: [], // what is the type????
    address: [], // what is the type????
  },
  offers2: '', // can there be offers 3/4/5 etc.?
  notice_send_date: '',
  notice_send_date_stamp: '',
  phone: '',
  fax: {},
  person: '',
  subject: '',
  date: '',
  submit_place: '',
  other_notes: '',
  notice_cpv_type: '',
  price: '',
  eu_authority: '',
  attachments: {
    file: {
      name: '',
      content: '',
    },
  },
  info_places: '', // type ?
  basic_contract_sum_value: '',
  contract_amount: '',
  contract_price_from: '',
  contract_price_to: '',
  contract_currency: '',
  options: '',
  options_description: '',
  options_months: '',
  options_days: '',
  renewal_times: '',
  renewal_times_from: '',
  renewal_times_to: '',
  delivery_timetable_months: '',
  delivery_timetable_days: '',
  contract_months: '',
  contract_days: '',
  contract_start_date: '',
  contract_end_date: '',
  supplement_2: {
    region: '',
    basic_contract: '',
    currency: '',
    state_procurement: '',
  },
  supplement_2b: { // what kind of supplement types are there?
    place: '',
    region: '',
    service_types: '',
    basic_contract: '',
    description: '',
    price_exact: '',
    notes: '',
    price_from: '',
    price_to: '',
    currency: '',
    procedure_start_date: '',
    months: '',
    days: '',
    start_date: '',
    end_date: '',
    state_procurement: '',
  },
  supplement_3_4: {
    prof_qualification: '',
    prof_qual_text: '',
  },
  supplement_3: {
    guarantee: '',
    financial_rules: '',
    groups: '',
    other_conditions: '', // type?
    other_conditions_details: '',
    businessman_requirements: '',
    financial_requirements: '',
    financial_requirements_min: '',
    technical_requirements: '',
    technical_requirements_min: '',
    reserved: '',
  },
  procedure: {
    proc_type: '',
    argument: '',
    candidates_selected: '', // boolean
    count_restrictions: '', // type?
    tenderer_count_expected: '',
    criteria: '',
    tenderer_count_min: '',
    tenderer_count_max: '',
    tenderer_decrease: '',
    candidates: { // can this be an array?
      name: '',
      reg_nr: '',
      country: '',
      city: '',
      address: '',
    }
  },
  auction_description: '',
  variants: '', // type?
  administrative_info: {
    oj_digital: '', // boolean
    digital_access: '', // boolean
    previous_publications: '', // boolean
    previous_publications_oj: '', // boolean
    previous_publications_other: '', // boolean
    urgent: '', // boolean
    urgent_text: '',
    oj_list: '',
    publication_list: '',
    submit_date: '',
    submit_hour: '',
    submit_minute: '',
    send_date: '',
    submit_date_stamp: '',
    document_request_date: '',
    document_request_hour: '',
    document_request_minute: '',
    payment: '', // type?
    language: '',
    tender_open_date: '',
    tender_open_hour: '',
    tender_open_minute: '',
    tender_open_place: '',
    allowed: '', // type?
    allowed_persons: '',
  },
  submit_hour: '',
  submit_minute: '',
  cancel_user: '',
  first_approval_date: '',
  first_approval_date_stamp: '',
  new_scopes: {},
  middleman_list: {
    middleman_item: {
      auth_id: '',
      name: '',
      reg_num: '',
      address: '',
      city: '',
      zip_code: '',
      country: '', // country num ('1' for LV etc.)
    },
  },
  field_description: '',
  field_note: '',
  field_a: '',
  field_b: '',
  field_c: '',
  field_d: '',
  field_e: '',
  field_e1: '', // ????
  field_e2: '', // ????
  field_f: '',
  field_g: '',
  field_h: '',
  field_i: '',
  field_j: '',
  field_k: '',
  field_l: '',
  field_m: '',
  field_a_81: '',
  field_b_81: '',
  field_c_81: '',
  field_d_81: '',
  field_e_81: '',
  field_f_81: '',
  field_g_81: '',
  field_h_81: '',
  field_i_81: '',
  field_j_81: '',
  field_k_81: '',
  field_l_81: '',
  field_m_81: '',
  field_n_81: '',
  field_o_81: '',
  field_soc_a: '',
  field_soc_b: '',
  field_soc_c: '',
  field_soc_d: '',
  field_soc_e: '',
  field_soc_f: '',
  field_soc_g: '',
  timelimits: {
    dok_req_date: '',
    work_time: '',
    submit_hour: '',
    submit_minute: '',
    tender_open_date: '',
    tender_open_hour: '',
    tender_open_minute: '',
    tender_open_place: '',
    submit_date: '',
    submit_date_stamp: '',
  },
  submit_date_stamp: '',
  submit_date: '',
  tender_for_parts: '', // boolean
  info: '',
  end_date: '',
  start_date: '',
  days: '',
  months: '',
  language: '',
  middleman_search_name: {},
  documentation_online: '', // boolean ('0' or '1')
  submit_places: '', // boolean ('0' or '1')
  doc_places: '', // boolean ('0' or '1')
  content: '',
  service_type: {},
  extra_winners: '', // boolean ('0' or '1')
  extra_winners_reason: '',
  contract_expects: '',
  notes: '',
  environment_req_detail: '',
  no_doc_ext: '',
  send_oj: '',
  service_types: '',
  state_procurement: '',
  criteria_type: '',
  proc_type: '',
  update_date: '',
  update_date_stamp: '',
  publicate: '',
  price_from: '',
  price_to: '',
  with_vat: '',
  vat_rate: '',
  price_exact_lvl: '',
  building_types: '',
  supply_types: '',
  previous_publications: '',
  previous_publications_oj: '',
  previous_publications_other: '',
  auction: '',
  argument: {},
  criteria_list: {},
  oj_list: {},
  oj_digital: '',
  publication_list: {
    publication: {
      pub_date: '',
      pub_type: '',
    }
  },
  has_complaint: '',
  complaint_id: '',
  checker_id: '',
  checking_started: '',
};